-------------NA VPS------
1-- COLOQUE A PASTA api DENTRO DA SUA VPS

2-- BAIXE O PROGRAMA NODE JS

3-- ABRA A PORTA 3000 NA SUA VPS (OU EXECUTE O ARQUIVO "Abrir_portas.lua" DENTRO DA SUA VPS)

3-- VÁ NA PASTA api E EXECUTE O ARQUIVO som.sql no HEIDSQL, IRÁ GERAR O BANCO DE DADOS "lafy"

4-- AINDA NA PASTA api VÁ NO ARQUIVO config.json E EM "SERVER"-"Host" COLOQUE O IP DA SUA VPS

5-- NA PASTA api EXECUTE O ARQUIVO START.BAT


--------- NA BASE -------

1-- Vá na pasta [scripts]/lafy/dist/app.js E PROCURE POR "SEU_IP" E COLOQUE SEU IP